[project]
name = "FFDB"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"aiofiles>=23.2.1",
	"aiohttp>=3.9.5",
	"duckdb>=1.0.0",
	"pandas>=2.2.2",
	"pyarrow>=16.1.0",
	"python-dotenv>=1.0.1",
	"requests>=2.32.3",
	"tqdm>=4.66.4",
	"typer>=0.12.3",
]

[project.scripts]
ffdb = "cli.main:app"

[tool.setuptools]
packages = ["cli", "extractors", "references"]
py-modules = ["config", "duck", "games", "helpers", "pipeline", "players"]